### ISSUE TITLE
Error on $shopify ftp

### ISSUE THREAD

**Issue by Sempaisan** [sstur/shopify-ftp#10]
Hello! I'm trying to run the shopify ftp command and I'm getting this weird error:
 
$ shopify ftp
util.js:961
    throw new TypeError('The super constructor to "inherits" must not ' +
    ^

TypeError: The super constructor to "inherits" must not be null or undefined
    at Object.exports.inherits (util.js:961:11)
    at Object.<anonymous> (/usr/local/lib/node_modules/shopify-ftp/node_modules/ftpd/lib/ftpd.js:67:6)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at /usr/local/lib/node_modules/shopify-ftp/shopify.js:9:14

Anyone knows what could be the issue here ? Thanks

**Comment by wayofthefuture** [comment]
Same problem with FTPD over here no solution...

**Comment by wayofthefuture** [comment]
Solved by installing from GitHub:

> npm i https://github.com/sstur/nodeftpd.git --save
