### ISSUE TITLE
Can't launch this script(

### ISSUE THREAD

**Issue by cheshirrrcat** [sstur/shopify-ftp#11]
I have an error when I tried to launch from the terminal like **shopify ftp**

```
util.js:973
    throw new TypeError('The super constructor to "inherits" must not ' +
    ^

TypeError: The super constructor to "inherits" must not be null or undefined
    at Object.exports.inherits (util.js:973:11)
    at Object.<anonymous> (/usr/local/lib/node_modules/shopify-ftp/node_modules/ftpd/lib/ftpd.js:67:6)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at /usr/local/lib/node_modules/shopify-ftp/shopify.js:9:14
```

I have macOS Sierra 10.12.4
How can I overcome it?

**Comment by bxmas13** [comment]
The developer for shopify-ftp has not been updating the code.
At this point I would suggest using [Quickshot ](https://quickshot.readme.io/)or [Themekit](https://shopify.github.io/themekit/).

I use both as Quickshot allows me to download products/pages/blogs, and Themekit(using 'theme watch') I can use in my IDE's(PHPStorm) console.

**Comment by cheshirrrcat** [comment]
@bxmas13 Thanks a lot 🙌🏻🎉
