### ISSUE TITLE
on MacOS fine. Windows 8.1 - Error

### ISSUE THREAD

**Issue by Tusko** [sstur/shopify-ftp#2]
node v0.12.0
npm v2.5.1

I have error, when try to connect FTP

    SyntaxError: Unexpected end of input
    at Object.parse (native)
    at Request._callback (\\Downloads\shopify\node_modules\shopify-ftp\shopify.js:338:25)
    at Request.self.callback (\\Downloads\shopify\node_modules\shopify-ftp\node_modules\request\request.js:344:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (\\Downloads\shopify\node_modules\shopify-ftp\node_modules\request\request.js:1239:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (\\Downloads\shopify\node_modules\shopify-ftp\node_modules\request\request.js:1187:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

**Comment by sstur** [comment]
This is definitely an issue on Windows and several people have been able to reproduce. Some more detail is available in #6. I have a working Windows VM so I will try to find a fix, but I can't promise anything.

**Comment by sstur** [comment]
This error appears to be due to a `404 Not Found` getting returned from shopify api with content-type: application/json yet content-length is zero (so `JSON.parse` fails with an empty string as input). I'm looking into this.

    FTP server listening on 127.0.0.1:2121
    FTP connection from 127.0.0.1
    fetched themes
    readdir \
    headers { server: 'nginx',
      date: 'Sat, 17 Oct 2015 01:44:29 GMT',
      'content-type': 'application/json',
      'transfer-encoding': 'chunked',
      connection: 'close',
      vary: 'Accept-Encoding, Accept-Encoding',
      status: '404 Not Found',
      'x-frame-options': 'DENY',
      'x-shopid': '<redacted>',
      'x-shardid': '4',
      'x-shopify-shop-api-call-limit': '1/40',
      http_x_shopify_shop_api_call_limit: '1/40',
      'x-stats-userid': '0',
      'x-stats-apiclientid': '<redacted>',
      'x-stats-apipermissionid': '<redacted>',
      'x-xss-protection': '1; mode=block; report=/xss-report/d6c3d99f-2560-4737-8087-ea7e09358918?source%5Baction%5D=index&source%5Bcontroller%5D=admin%2Fassets&source%5Bsection%5D=admin',
      'set-cookie': [ 'request_method=GET; path=/' ],
      'x-request-id': 'd6c3d99f-2560-4737-8087-ea7e09358918' }

**Comment by sstur** [comment]
This is now fixed in v0.1.9 which is published on npm.
