### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by bxmas13** [sstur/shopify-ftp#8]
When trying to go into my assets directory(which contains a lot of files) I receive the "RangeError: Maximum call stack size exceeded" error.

Full error:

```
fetched assets for: ProjectTheme
C:\Users\MYUSERNAME\AppData\Roaming\npm\node_modules\shopify-ftp\shopify.js:418
  function StatsObject(type, item) {
                      ^

RangeError: Maximum call stack size exceeded
    at Object.StatsObject (C:\Users\MYUSERNAME\AppData\Roaming\npm\node_modules\shopify-ftp\shopify.js:418:23)
    at Object.<anonymous> (C:\Users\MYUSERNAME\AppData\Roaming\npm\node_modules\shopify-ftp\shopify.js:207:24)
    at Object.Proxy.getTheme (C:\Users\MYUSERNAME\AppData\Roaming\npm\node_modules\shopify-ftp\shopify.js:130:25)
    at Object.Proxy.stat (C:\Users\MYUSERNAME\AppData\Roaming\npm\node_modules\shopify-ftp\shopify.js:190:12)
    at Object.Proxy.(anonymous function) [as stat] (C:\Users\MYUSERNAME\AppData\Roaming\npm\node_modules\shopify-ftp\shopify.js:413:26)
    at handleFile (C:\Users\MYUSERNAME\AppData\Roaming\npm\node_modules\shopify-ftp\node_modules\ftpd\lib\glob.js:32:9)
    at C:\Users\MYUSERNAME\AppData\Roaming\npm\node_modules\shopify-ftp\node_modules\ftpd\lib\glob.js:40:9
    at Object.<anonymous> (C:\Users\MYUSERNAME\AppData\Roaming\npm\node_modules\shopify-ftp\shopify.js:207:9)
    at Object.Proxy.getTheme (C:\Users\MYUSERNAME\AppData\Roaming\npm\node_modules\shopify-ftp\shopify.js:130:25)
    at Object.Proxy.stat (C:\Users\MYUSERNAME\AppData\Roaming\npm\node_modules\shopify-ftp\shopify.js:190:12)
```

**Comment by sstur** [comment]
Hi. Thanks for reporting this. I believe it is related to https://github.com/sstur/nodeftpd/issues/101 which is the ftp library this is based on. I'll take a look and see if I can land a fix this week.
